@echo off
echo Starting EnterpriseRAG...

echo Starting Backend...
start cmd /k "cd backend && python -m venv venv && .\venv\Scripts\activate && pip install -r requirements.txt && python main.py"

echo Starting Frontend...
start cmd /k "cd frontend && npm install && npm run dev"
